# Generated by Django 3.1.5 on 2021-01-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriskras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tak', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vergadering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('extra', models.CharField(max_length=5)),
                ('activiteit', models.CharField(max_length=500)),
                ('Kriskras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kriskras')),
            ],
        ),
    ]
