# Generated by Django 3.1.5 on 2021-01-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vergadering',
            old_name='Kriskras',
            new_name='kriskras',
        ),
    ]
