# Generated by Django 3.1.5 on 2021-02-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210127_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vergadering',
            name='date',
            field=models.DateField(),
        ),
    ]
