# Generated by Django 3.1.5 on 2021-02-02 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210202_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vergadering',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 2), verbose_name='Date'),
        ),
    ]
