# Generated by Django 3.1.5 on 2021-02-02 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210202_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vergadering',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 13, 1, 11, 978770, tzinfo=utc), verbose_name='Date'),
        ),
    ]
