# Generated by Django 3.1.5 on 2021-02-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210202_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vergadering',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
